--------------------------------------------------------
--  Arquivo criado - Domingo-Julho-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONTA" 
   (	"ID" NUMBER(10,0), 
	"VALOR" VARCHAR2(225 BYTE), 
	"DATA_CONTA" DATE, 
	"ID_PES" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CONTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CONTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CONTA_PK" ON "SYSTEM"."CONTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTA" ADD CONSTRAINT "CONTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CONTA" MODIFY ("DATA_CONTA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTA" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTA" MODIFY ("ID_PES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTA" ADD CONSTRAINT "CONTA_FK1" FOREIGN KEY ("ID_PES")
	  REFERENCES "SYSTEM"."PESSOA" ("ID") ENABLE;
