--------------------------------------------------------
--  Arquivo criado - Domingo-Julho-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENDERECO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ENDERECO" 
   (	"ID" NUMBER(10,0), 
	"LOGRADOURO" VARCHAR2(225 BYTE), 
	"NUMERO" NUMBER(10,0), 
	"COMPLEMENTO" VARCHAR2(225 BYTE), 
	"ID_PES" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ENDERECO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ENDERECO_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ENDERECO_ID_PK" ON "SYSTEM"."ENDERECO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ENDERECO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ENDERECO" MODIFY ("ID_PES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ENDERECO" ADD CONSTRAINT "ENDERECO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ENDERECO" MODIFY ("COMPLEMENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ENDERECO" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ENDERECO" MODIFY ("LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ENDERECO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENDERECO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ENDERECO" ADD CONSTRAINT "ENDERECO_FK1" FOREIGN KEY ("ID_PES")
	  REFERENCES "SYSTEM"."PESSOA" ("ID") ENABLE;
