--------------------------------------------------------
--  Arquivo criado - Domingo-Julho-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PESSOA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PESSOA" 
   (	"ID" NUMBER(10,0), 
	"NOME" VARCHAR2(225 BYTE), 
	"TELEFONE" VARCHAR2(225 BYTE), 
	"EMAIL" VARCHAR2(225 BYTE), 
	"SEXO" VARCHAR2(225 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PESSOA
SET DEFINE OFF;
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('1','marreco','6666666','marreco@gmail.com','M');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('6','teste','teste','teste','teste');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('8','t','u','v','x');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('11','sergio','99999','sergin@gmail.com','M');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('12','hahahah','555555','email','F');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('14','ttttttttttttt','ggggggggggg','ffffff','dddddd');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('15','jjj','1111','3333','rrr');
Insert into SYSTEM.PESSOA (ID,NOME,TELEFONE,EMAIL,SEXO) values ('16','p','p','p','p');
--------------------------------------------------------
--  DDL for Index PESSOA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PESSOA_PK" ON "SYSTEM"."PESSOA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PESSOA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PESSOA" ADD CONSTRAINT "PESSOA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PESSOA" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PESSOA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PESSOA" MODIFY ("TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PESSOA" MODIFY ("NOME" NOT NULL ENABLE);
